### ISSUE TITLE
research: audit JOSE libraries in Python for ECDH-1PU compatibility

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#1]
We want people to be able to implement [ECDH-1PU Draft 4](https://datatracker.ietf.org/doc/html/draft-madden-jose-ecdh-1pu-04) using a standard JOSE library in Python. When we implemented Draft 3 of that RFC in Rust, we were able to do it with just [a few lines of code](https://github.com/andrewwhitehead/aries-askar/commit/17a4e0fbcb961b0e5d1f375b287681af982eb0ef#diff-c1f73351aa42c3dca3eafea450fcbdaa63000001c8f489aa11fae2b3d7f754d3R53); the purpose of this ticket is to decide whether it is true in Python. If it is not true, we need to discuss the best way to patch the libraries -- contribute a patch to mainstream JOSE libraries, fork the mainstream JOSE libraries and add our feature, or write a very simple version of JOSE that's adequate for DIDComm with ECDH-1PU only.

**Success Criteria**
- Write a doc (this repo Wiki) with the research summary
- The doc should contain multiple Options with cons and pros how we can implement ECDH-1PU for the target language
- There should be one proposed option that we can discuss and approve with the team
- Take into account the following when describing the existing libraries:
  - Whether all required curves required for DID Comm are supported (X25519 is must have for the first release; P-256 and P-384 will also be needed)  
  - What encryption protocols required for DID Comm are supported in the library (XC20P, A256GCM, A256CBC-HS512)
  - What signature protocols required for the DID Comm are supported in the library (EdDSA (with crv=Ed25519), ES256, ES256K)
  - What Key Wrapping algorithms required for the DID Comm are supported (ECDH-ES+A256KW)
  - License, compatibility with Apache 2, possible need for modifications of the library 
  - Whether the library is open or closed to external contributions
  - How ECDH-1PU can be supported: 
       - contribution to the upstream
       - support in a fork (no upstream contribution for now)
       - implement in DID Comm lib code on top of JOSE lib
  - What base crypto lib will be used 
  - Are there any know security issues in the lib? How popular is the lib?

**Comment by asmarty** [comment]
I completed research for Python's JOSE libraries.  You can find result [here](https://hackmd.io/qJhPmgM3RIOy1D_evwjQHg). 

According this research it seems to me there are 2 options:
1. We include [PyJWT](https://github.com/jpadilla/pyjwt/) and implement JWE over this library
2. We implement necessary part of JOSE spec without JOSE library.  [pyca/cryptography](https://pyjwt.readthedocs.io/en/latest/) can be used as crypto lib

**Comment by asmarty** [comment]
@ashcherbakov found out that PyJWT uses Compact serelization. So in this case option 2 looks better then 1

**Comment by dhh1128** [comment]
We are likely to need support for JWKs in order to use JsonWebKey2020 from DID docs. Therefore I think using PyJWT may be less effort. Could we contribute our support for JWE back to PyJWT?

The research report tells me what the technical tradeoffs are, but not what the tradeoffs are in two additional dimensions that are iimportant:

1. How much work is involved in each of the alternatives?
2. How likely is it that our implementations will be the source of vulnerabilities, in each of the alternatives?

Could you please provide some detail about those questions before we decide?

**Comment by asmarty** [comment]
We cannot use PyJWT as it is. We need to make a fork or try to contribute the next features:
1. Support the jJWT (I think if we contribute, then we need to support all the algorithms that are in the specification but we need only part of them)
2. In JWS add json serialization (now the library only support compact searilization)
3. In the JWK, add saving a key in the JWK format (the library only supports loading the key from jwk)
In my opinion, we have to do a lot of work for this library. But there are two issues refer JWE implemetation, so I guess we can try to contribute. Not sure if we save hours.


If we look at other libraries, autlib includes a lot of unnecessary dependencies like oauth. On top of that, we also need to modify API for JWE. So in this case we need to fork.

Jwcrypto - I think we will not be able to use this library due to licensing

Python-jose. We need to add many functions to this library, ed25519 to sign and support the ecdh-es, ecdh-1pu, etc. algorithms.

So, all libraries require contribution. If we implement from scratch, In my opinion,  we will not get as many problems with security, because we are going to use exists cryptography, in addition, we will try to cover more functionality with tests.

**Comment by dhh1128** [comment]
Okay, thank you for the additional detail.

>f we implement from scratch, In my opinion, we will not get as many problems with security, because we are going to use exists cryptography, in addition, we will try to cover more functionality with tests.

The problem is that, although it may look like we don't have as many security issues on the day we finish coding, we will be creating a codebase that has no maintainers -- so any future security vulnerabilities will remain unfixed forever. Whereas if we contribute to PyJWT, the library has maintainers that (we hope) will react if security issues are found.

This is more than just a security maintenance issue, though. It's true of everything about the library. Although we may write something cleaner and with better tests, if we produce something that has zero maintainers, it is probably a mistake.

So I see two rational choices:

Option 1: fork PyJWT. Add to our fork *only* the features we need, and raise a PR back to the upstream library -- so that if our PR is accepted, the maintainers of PyJWT can get JSON serialization and the ability to save JWKs, plus limited JWE support. Do NOT attempt to add JWE with all the algorithms that are in the specification. The maintainers of PyJWK should accept our contribution if they are smart, even if it's less than everything they want. And we don't have to maintain things very much.

Option 2: Write our own from scratch, possibly copying and pasting code from other places. This means we have no story for maintenance and security vulns, and we have to set up CI/CD plus pypi publication for an entirely new project.

I would only select option 2 if it is significantly (like 3x, 5x, etc) better in terms of effort or security than option 1. Is it? Or is it only 25% easier or cleaner?

**Comment by vimmerru** [comment]
> The maintainers of PyJWK should accept our contribution if they are smart, even if it's less than everything they want. And we don't have to maintain things very much.

I suggest to ask rising question on PyJWK repo. I don't see any value in our contribution for PyJWT. They main and only use case is sign JWT auth token for web project. So with 90+% of probability we will get fork that doesn't make sense outside of DIDComm library and will need to support all PyJWK codebase.

**Comment by dhh1128** [comment]
Okay, I have asked the maintainer of PyJWT what he thinks. I tagged @vimmerru and @ashcherbakov in my issue on his repo; let's see what he says.

If we end up not using PyJWK, then I'd like to bundle the functionality we need directly into the python DIDComm lib, so we don't have to set up CI/CD or vulnerability management or maintainership for a separate project.

**Comment by ashcherbakov** [comment]
@dhh1128 
Just to make sure that we are on the same page:
Both options 1 and 2 proposed in this thread (https://github.com/sicpa-dlab/didcomm-gemini/issues/1#issuecomment-883234362) are not about creating a separate JOSE library with zero maintainers, but about implementing required JOSE stuff right in **Python DID Comm repo**.

So, in Option 1 we assumed that we use PyJWK as a dependency (as-is) in Python DIDComm, and implement missing JOSE functionality in Python DID Comm.
In Option 2 we don't use PyJWK as a dependency at all (since it looks like it gives us almost nothing useful, we can not use JWS as-is from there, and JWK is just a couple lines of code), so we (the same way as in Option 1) implement required JOSE features in Python DID Comm.

**Comment by ashcherbakov** [comment]
- Python research: [link](https://hackmd.io/qJhPmgM3RIOy1D_evwjQHg)
- Our proposal: [link](https://hackmd.io/7c1bcf0LTQ2xvXkDzcesZQ)
