### ISSUE TITLE
DIDComm Java/Kotlin: Android support

### ISSUE THREAD

**Issue by ashcherbakov** [sicpa-dlab/didcomm-gemini#79]
## Success Criteria
- Build DIDComm for Android
- CI must check that the build is correct
- Release DIDComm Android (probably as a separate artifact in addition to common Java/Kotlin)
- Consider adding an instrumented test to check the basic lib functionality on Android device; run the test in CI if it's easily possible.

**Comment by spivachuk** [comment]
We want to use the sole source code tree for both JDK and Android builds. For this we propose to add modules for each of the builds: `jdk_app` and `android_app`, and reference the same source code roots from them. The same test code should be referenced by `java.sourceSets.test.java.srcDir` property of `jdk_app` module `build.gradle` and by `android.sourceSets.androidTest.java.srcDir` property of `android_app` module `build.gradle`.

To run JUnit 5 tests on Android [android-junit5](https://github.com/mannodermaus/android-junit5) plugin can be used. Test runner annotations should not be specified at test classes because different ones will be used by `jdk_app` and `android_app` modules. Instead the test runner should be overridden by `android.defaultConfig.testInstrumentationRunner` property of `android_app` module `build.gradle`.

**Comment by andkononykhin** [comment]
https://github.com/sicpa-dlab/didcomm-jvm/pull/10 implements the most part of the task:
- makes possible to run the same set of tests (we have for JVM) on android emulator
- no special build (and release) for didcomm lib is required

I tend to move CI related things (only test run is considered here) to https://github.com/sicpa-dlab/didcomm-gemini/issues/94 as an additional point
