### ISSUE TITLE
requirements: write spec for didcomm.org website

### ISSUE THREAD

**Issue by dhh1128** [sicpa-dlab/didcomm-gemini#9]
We need a summary of the requirements for the didcomm.org website.

**Comment by dhh1128** [comment]
First cut is here: https://hackmd.io/@dhh1128/ryOJER-6O/edit

**Comment by dhh1128** [comment]
I have maintainer rights to the didcomm.org website and can help others get access if needed.

**Comment by ashcherbakov** [comment]
@dhh1128 
Can you please give access to didcomm.org to Stanislav Zhatikov (@Merciful12) who will be the main developer of the web site?

Also we have a couple of questions about requirements:
1) https://github.com/decentralized-identity/didcomm.org#license says that every commit (and hence every new Protocol Definition markdown PR) needs to be signed. Is it a must-have requirement?
2) We were thinking about an option to integrate a CMS that works with GitHub pages (for example https://www.netlifycms.org/, and https://www.netlifycms.org/docs/jekyll/). It may provide a better user experience for registering new protocol definitions (to do it via CMS, and not via PRs). What do you think about that option and UX?
A possible drawback here is that Netlify CMS doesn't support signed commits (https://github.com/netlify/netlify-cms/issues/3284).

**Comment by ashcherbakov** [comment]
3. Another question: is it expected that a PR with a new protocol definition merged automatically once all tests passed, or a manual approval and a need to press the Merge button by someone will be required?

**Comment by dhh1128** [comment]
Regarding giving Stanislav access: I don't think he needs any access. Anybody can raise a PR. I can make sure the PRs get accepted. What else does he need?

Regarding #1: We should explore whether we can change this. It is currently configured that way because of a DIF policy. I will open an email thread about it and include you and Stanislav.

Regarding #2: Since the people we are talking about are developers, I'm not sure it's important to avoid the PR experience. But I'm willing to look into it. Our ability to use a CMS will depend on whether or not we can eliminate the requirement to sign all commits. So we have to answer question #1 first, I guess.

**Comment by dhh1128** [comment]
Regarding #3: It is desirable that a new protocol definition would be merged automatically. However, our willingness to do that may depend on the quality of the tests we have. So we should only propose an automatic flow if we have thought carefully about what the tests can guarantee.

**Comment by dhh1128** [comment]
I would like this reviewed by @ashcherbakov and @telegramsam.

**Comment by Merciful12** [comment]
@dhh1128 
Regarding the search functionality. If we are implementing a client side search (because there is no way to predict search results on build time) it can lead to performance issues on considerably large data (list of protocols). That's probably not a problem for MVP when the number of registered protocol definitions is not significant, but may become a problem later when we will have thousands of protocol definitions.

**Comment by dhh1128** [comment]
I agree that this is a scaling constraint.

I would design the system so it works well with hundreds of protocols, and works adequately for a thousand or two. If we get to a state where we have more than a few thousand registered protocols, it will be time to implement a server-based back end for the web site -- for the search feature, anyway. That will be a good problem to have. But let's not solve it now.

**Comment by ashcherbakov** [comment]
The requirements look full and clear for us. The user stories have been created based on the requirements.

**Comment by vimmerru** [comment]
> Regarding the search functionality. If we are implementing a client side search (because there is no way to predict search results on build time) it can lead to performance issues on considerably large data (list of protocols). That's probably not a problem for MVP when the number of registered protocol definitions is not significant, but may become a problem later when we will have thousands of protocol definitions.

I think static site builders can be relatively easy integrated with client side search based on pre-built indexes. For example, https://www.gatsbyjs.com/docs/adding-search-with-js-search/

**Comment by ashcherbakov** [comment]
@dhh1128 (FYI @Merciful12 )
We have a question about the last requirements with tags from [Best-practices-and-CICD](https://hackmd.io/s8LmceVRRf-23iTKCy7X8A#Best-practices-and-CICD).

> Hashtags represent meaningful differences (we don’t want one protocol tagged with #finance and another tagged with #financial or #finances

It looks like it can be difficult to decide automatically what makes a meaningful difference. Please find the example of the issue and possible options how to deal with this.

My recommendation would be to go with Option 2: show a warning with a list of suggestions not preventing the merge. Also I would consider this requirement as a nice-to-have rather than must-have. If we realize that it makes too much time to implement it, we may just skip it for the first release (I believe we should use some NLP-like lib to do the checks automatically, but still).

**Example:**
- The very first protocol is published with a tag `#finances`. There are no similar tags so far, so CI will let the PR to be merged.
- The next protocol is going to be published. It wants to add a tag `#finance`, but as there is already #finances tag, CI will warn the user. However, the author of the second protocol may have good arguments why #finance is better than #finances, so he doesn't want to change the tag.

It seems it's pretty hard to deal with this situation automatically. And I believe it's not a common practice to restrict the user in attaching the tags that they want. I think usually either a list of pre-defined tags is provided (not our case as we don't know in advance), or the software just makes some suggestions (provides a list of similar tags for example so that the user is aware and can choose).

**Options**
1) Option 1: just don't implement any restrictions on tags at all.
Let's not try to be too smart to restrict and annoy the users. 

2) Option 2: show a warning with a list of suggestions not preventing the merge
CI checks if there are any similar tags already available. If they are found, a warning is shown in the PR with a list of similar tags the user can consider to attach (or replace existing by the found ones). But it's up to the user to follow this recommendations. The warning doesn't restrict the PR from being merged. 

3) Option 3: show an error with a list of suggestions preventing the merge
CI checks if there are any similar tags already available. If they are found, an error is shown in the PR with a list of similar tags. The PR can not be merged until it's resolved.
I believe this is not acceptable option due to the Issue and Example mentioned above.

**Comment by dhh1128** [comment]
Let's do option 2. For similar tags, let's display any existing tag that has a [Damerau-Levenshtein edit distance](https://en.wikipedia.org/wiki/Edit_distance) <= 1/3 the size of the new tag.

Code from https://www.guyrutenberg.com/2008/12/15/damerau-levenshtein-distance-in-python/:

```python
"""
Compute the Damerau-Levenshtein distance between two given
strings (s1 and s2)
"""
def damerau_levenshtein_distance(s1, s2):
    d = {}
    lenstr1 = len(s1)
    lenstr2 = len(s2)
    for i in range(-1,lenstr1+1):
        d[(i,-1)] = i+1
    for j in range(-1,lenstr2+1):
        d[(-1,j)] = j+1

    for i in range(lenstr1):
        for j in range(lenstr2):
            if s1[i] == s2[j]:
                cost = 0
            else:
                cost = 1
            d[(i,j)] = min(
                           d[(i-1,j)] + 1, # deletion
                           d[(i,j-1)] + 1, # insertion
                           d[(i-1,j-1)] + cost, # substitution
                          )
            if i and j and s1[i]==s2[j-1] and s1[i-1] == s2[j]:
                d[(i,j)] = min (d[(i,j)], d[i-2,j-2] + cost) # transposition

    return d[lenstr1-1,lenstr2-1]


if __name__ == '__main__':
    import sys
    while True:
        sys.stdout.write("Type a word pair: ")
        words = [x.strip() for x in input().split(',')]
        print('DL Edit Distance is %s.' % damerau_levenshtein_distance(words[0], words[1]))  
```

**Comment by dhh1128** [comment]
Update: let's compute edit distance *after* subtracting all punctuation (so we're only comparing edit distance for alphanumerics).
